[module.hugoVersion]
min = "0.111.3"
# extended = true

[outputFormats]
[outputFormats.DecapCMSConfig]
baseName = "decap-cms-config"
isHTML = false
notAlternative = true
mediaType = "application/yaml"

[params.decap_cms]
js_url = ""
# local_backend = false
publish_mode = "editorial_workflow"
media_folder = "static/images/uploads"
public_folder = "/images/uploads"
search = true
_preview_styles = []

[params.decap_cms._configs.field_body.fields.body]
name = "body"
label = "Body"
widget = "markdown"

[params.decap_cms._configs.field_categories.fields.categories]
name = "categories"
label = "Categories"
required = false
widget = "list"
summary = "{{fields.category}}"
collapsed = true
minimize_collapsed = true
[params.decap_cms._configs.field_categories.fields.categories.field]
label = "Category"
name = "category"
widget = "string"

[params.decap_cms._configs.field_date.fields.date]
name = "date"
label = "Date"
widget = "datetime"
picker_utc = true

[params.decap_cms._configs.field_description.fields.description]
name = "description"
label = "Description"
widget = "text"

[params.decap_cms._configs.field_draft.fields.draft]
name = "draft"
label = "Draft"
default = true
widget = "boolean"

[params.decap_cms._configs.field_images.fields.images]
name = "images"
label = "Images"
required = false
widget = "list"
summary = "{{fields.image}}"
collapsed = true
minimize_collapsed = true
[params.decap_cms._configs.field_images.fields.images.field]
label = "Image"
name = "image"
widget = "image"

[params.decap_cms._configs.field_keywords.fields.keywords]
name = "keywords"
label = "Keywords"
required = false
widget = "list"
summary = "{{fields.keyword}}"
collapsed = true
minimize_collapsed = true
[params.decap_cms._configs.field_keywords.fields.keywords.field]
label = "Keyword"
name = "keyword"
widget = "string"

[params.decap_cms._configs.field_layout.fields.layout]
name = "layout"
label = "Layout"
required = false
widget = "string"

[params.decap_cms._configs.field_series.fields.series]
name = "series"
label = "Series"
required = false
widget = "list"
summary = "{{fields.series}}"
collapsed = true
minimize_collapsed = true
[params.decap_cms._configs.field_series.fields.series.field]
label = "Series"
name = "series"
widget = "string"

[params.decap_cms._configs.field_slug.fields.slug]
name = "slug"
label = "Slug"
required = false
widget = "string"

[params.decap_cms._configs.field_tags.fields.tags]
name = "tags"
label = "Tags"
required = false
widget = "list"
summary = "{{fields.tag}}"
collapsed = true
minimize_collapsed = true
[params.decap_cms._configs.field_tags.fields.tags.field]
label = "Tag"
name = "tag"
widget = "string"

[params.decap_cms._configs.field_title.fields.title]
name = "title"
label = "Title"
widget = "string"

[params.decap_cms._configs.field_type.fields.type]
name = "type"
label = "Type"
required = false
widget = "string"
