{{- $params := .Site.Params.decap_cms -}}
{{- $config := newScratch -}}
{{/* Reading settings from configuration. */}}
{{- $keys := slice
  "backend" "i18n" "local_backend" "locale" "logo_url" "media_folder"
  "public_folder" "publish_mode" "search"
-}}
{{- range $keys -}}
  {{- $key := . -}}
  {{- if isset $params $key -}}
    {{- $config.Set $key (index $params $key) -}}
  {{- end -}}
{{- end -}}
{{/* Transform collections. */}}
{{- with index $params "collections" -}}
  {{- range . -}}
    {{- $config.Add "collections" (slice .) }}
  {{- end -}}
{{- end -}}
{{/* Set the site URL. */}}
{{- $config.Set "site_url" site.BaseURL -}}
{{/* Use site language as the locale if not set. */}}
{{- if not ($config.Get "locale") }}
  {{- $locale := partialCached "decap-cms/functions/locale" . }}
  {{- $config.Set "locale" $locale }}
{{- end }}
{{/* Transform Logo URL. */}}
{{- with $config.Get "logo_url" }}
  {{- $logoURL := urls.Parse . }}
  {{- if eq $logoURL.Scheme "" }}
    {{- with resources.Get . }}
      {{- $config.Set "logo_url" .Permalink }}
    {{- else }}
      {{- $config.Set "logo_url" (. | absURL) }}
    {{- end }}
  {{- else }}
    {{- $config.Set "logo_url" . }}
  {{- end }}
{{- end }}
{{- transform.Remarshal "yaml" $config.Values | safeHTML -}}
