[[module.imports]]
path = "github.com/hugomods/decap-cms"

[params.hugopress.modules.decap-cms-netlify-identity.hooks.head-end]

[params.hugopress.modules.decap-cms-netlify-identity.hooks.body-end]

[params.hugopress.modules.decap-cms-netlify-identity.hooks.decap-cms-head-end]
cacheable = true

[params.decap_cms._netlify_identity]
js_url = "https://identity.netlify.com/v1/netlify-identity-widget.js"
